### ISSUE TITLE
Cannot run regboss'ed file

### ISSUE THREAD

**Issue by nminh185** [Fadi002/regboss#1]
Hello there,

Im having a problem using regboss to hide my code, my program has many .py files and I need to hide one .py file in the folder. And then, the problem is it my program is not running correctly for some reasons.
I don't know why it is not running correctly but with the same file before being obfuscated, the program works perfectly.
Hope to receive your help, thank you

**Comment by Fadi002** [comment]
can you send me screenshot of your problem ?

**Comment by nminh185** [comment]
Hi there
The normal code when run will be like this, it requires the user to press any button to run then the code will be processed
![image](https://user-images.githubusercontent.com/78833237/189520978-e3871dc2-f8e7-4cc8-b763-259d859e92aa.png)

But somehow my friend's comp when he runs the obfuscated code, it straight up ends and no program processed (image below)
![image](https://user-images.githubusercontent.com/78833237/189521283-1956bec1-aa92-4383-ae59-1d8d10f14101.png)

My main program requires class imported from need-to-be-obfuscated file. There are some guys can run the obfuscated file smoothly but still have a few can not.
Is this problem a random computer error or something like that?
Thank you.

**Comment by Fadi002** [comment]
hmmmmm try use hyperbreak project that i made : https://github.com/Fadi002/HyperBreak

**Comment by nminh185** [comment]
OH LOLLLLLLLLL. It worked like a charm!
Thank you so much.
Keep up the good work!

**Comment by Fadi002** [comment]
Np, thank you for using this project!
